# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: this-project-is-not-accepting-sponsors # Replace with a single Patreon username
open_collective: this-project-is-not-accepting-sponsors # Replace with a single Open Collective username
ko_fi: this-project-is-not-accepting-sponsors
tidelift: this-project-is-not-accepting-sponsors
community_bridge: this-project-is-not-accepting-sponsors
liberapay: this-project-is-not-accepting-sponsors
issuehunt: this-project-is-not-accepting-sponsors
otechie: this-project-is-not-accepting-sponsors
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
